### ISSUE TITLE
小哥，那个keynote的效果到底怎么实现的啊

### ISSUE THREAD

**Issue by Tasselmi** [MrFuFuFu/assignment2-keynote#1]
我的博客页面时直接挂在阿里云服务器上的，打开速度很快。不是挂在github.io上面。
但是那个keynote到底是怎么实现的啊我去。。。。。。。。。。。。。。至今懵逼中。
我把hux的项目复制到我的git下面，然后更换keynote中的链接地址，结果直接页面打不开了。
help me~~

**Comment by MrFuFuFu** [comment]
阿里云的我就不知道了，我是在 GitHub 上的，然后直接在 keynote 的 repository 里建一个 gh-pages 的分支。然后 repository 的名字就是我的 keynote 的链接后缀了。

**Comment by Tasselmi** [comment]
好的，谢谢。我已经弄出来了。非常感谢


| |
梁凡
邮箱：tasselmi@yeah.net
|

签名由 网易邮箱大师 定制

在2018年12月20日 04:07，Yuan Fu 写道：

阿里云的我就不知道了，我是在 GitHub 上的，然后直接在 keynote 的 repository 里建一个 gh-pages 的分支。然后 repository 的名字就是我的 keynote 的链接后缀了。
